 #AULA 01 - COMENTARIOS
 
 #PARA COMENTARIOS DE UMA LINHA
 #COMENTARIO EM OUTRA LINHA
 
 
 """
PARA COMENTARIO EM VARIAS LINHAS
PARA COMENTARIO EM VARIAS LINHAS 
PARA COMENTARIO EM VARIAS LINHAS
PARA COMENTARIOS EM VARIAS LINHAS 
 
 """